#!/bin/bash
#
# EZ Installer. Run from the bash command line:
#
#    curl -L https://raw.githubusercontent.com/gitbls/pistrong/master/EZPiStrongInstaller | bash

echo "This script is no longer used"
exit

[ "$EUID" -eq 0 ] && sudo="" || sudo="sudo"
$sudo curl -L https://raw.githubusercontent.com/gitbls/pistrong/master/pistrong -o /usr/local/bin/pistrong
$sudo curl -L https://raw.githubusercontent.com/gitbls/pistrong/master/InstallPiStrong -o /usr/local/bin/InstallPiStrong
$sudo curl -L https://raw.githubusercontent.com/gitbls/pistrong/master/makeMyCA -o /usr/local/bin/makeMyCA
$sudo curl -L https://raw.githubusercontent.com/gitbls/pistrong/master/makeTunnel -o /usr/local/bin/makeTunnel
$sudo chmod 755 /usr/local/bin/{pistrong,InstallPiStrong,makeMyCA}
$sudo /usr/local/bin/InstallPiStrong all < /dev/tty
